[font]
size = 11.0

[font.normal]
family = "JetBrains Mono"
style = "Regular"

[window]
opacity=0
decorations="None"
dynamic_padding=true
blur=true # only works on macOS/wayland
decorations_theme_variant="Dark"

[window.padding]
x=4
y=0

[colors]

[selection]
save_to_clipboard = true

[cursor.style]
shape = "Block"
blinking = "On"

